### ISSUE TITLE
Where is the class "BindableStore" used in MainStore.swift

### ISSUE THREAD

**Issue by kshivang** [SwiftRex/SwiftUI-ReduxCount#1]
Where is the class "BindableStore" in SwiftUI-ReduxCount/SwiftRexUI/Redux/MainStore.swift?

**Comment by kshivang** [comment]
Okay find it you renamed it to ObservableViewModel. [https://github.com/SwiftRex/SwiftRex/commit/10e5a7a98e9064c8e097c87c3ff6db3ab1c37bbe](here)

Better if you update in this project as well.

**Comment by luizmb** [comment]
Hi @kshivang,

Yes, I'm behind the changes with all example apps and also the Middleware projects. I'm sorry about the breaking changes, it's gonna be better once I release 1.0.

Can you open a PR for fixing that, please?

**Comment by luizmb** [comment]
Middleware will also break, now they are generic over 2 actions (input and output) and they receive the context (getState + action dispatcher) in a separate method.

**Comment by kshivang** [comment]
Hey @luizmb 

I am encountering two major problems creating this PR.
i) `lift(_:)` function missing in LiftMiddleware
ii) `convenience init(initialState:, reducer:, middleware:)` in ObservableViewModel is missing as well

For i) I tried using, `lift(inputActionMap:, outputActionMap:, stateMap:)`  instead, 
````swift 
lift(inputActionMap: { $0 }, outputActionMap: { $0 }, stateMap: { $0[keyPath: \MainState.countState] = $1 })
````  
but this is throwing, "Cannot convert value of type '_' to closure result type 'CountMiddleware.InputActionType?' (aka 'Optional<CountEvent>')"

For ii) I instead started to use `init(initialState:, store:)`. To create store I tried using ReduxStoreBase, but it didn't support Middleware with different Input and Output Action Types.

**Comment by luizmb** [comment]
Hi @kshivang,

Thanks for the attempt! I'm gonna update tonight and open the PR so you can see all that has changed in the API.

Please give me a couple of hours and I should finish it.

**Comment by luizmb** [comment]
Hi @kshivang,

Please check PR: https://github.com/SwiftRex/SwiftUI-ReduxCount/pull/2/
While writing this PR it got very clear that this Middleware is useless, but I didn't want to remove it because it's part of the example so I gave it a very fool purpose (this Event -> Action translation should be a Presenter, not a Middleware, but anyway...)

Please go through the code checking the changes and don't hesitate to comment the PR with things that are not clear. I can also (slowly) extend this example to demonstrate more complex applications, as I'm using SwiftRex for a loooong time and faced all sorts of things by now.

I would also appreciate if you could give a feedback about your experience with it, or even write your own examples. My time currently is very limited but I will support all kinds of contributions to this project with a very high priority, especially contributions with docs, examples, ideas, playgrounds and reusable middlewares.

I'm about to open source lots of tools for SwiftRex as well, things we use in complex apps to make life easier (Xcode file templates, debugging tools, Sourcery templates, SwiftUI extensions, reusable middlewares, etc).
